### ISSUE TITLE
Curious about build Instructions for OpenCV 

### ISSUE THREAD

**Issue by aswinkumar1999** [its-pointless/its-pointless.github.io#48]
Hi,
Found your OpenCV package to be very useful, when i tried the same to compile from source, I couldn't get the Install path for Python, I would like to know the instructions for the same.

Here are the Cmake Flags I used : 

```bash
$ 
$ LDFLAGS=" -llog -lpython3 " \
cmake \
-DBUILD_JAVA=OFF \
-DCMAKE_BUILD_TYPE=RELEASE \
-DCMAKE_INSTALL_PREFIX=$PREFIX \
-DBUILD_opencv_python3=on \
-DBUILD_opencv_python2=off \
-DWITH_QT=OFF -DBUILD_ANDROID_EXAMPLES=OFF \
-DWITH_GTK=OFF \
-D PYTHON3_NUMPY_INCLUDE_DIRS=$(python3 -c "import numpy; print(numpy.get_include())") \
-D PYTHON3_LIBRARY=$(python3 -c "import distutils.sysconfig as sysconfig; import os; print(os.path.join(sysconfig.get_config_var('LIBDIR'), sysconfig.get_config_var('LDLIBRARY')))") \
-D PYTHON3_INCLUDE_DIR=$(python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") \
-D PYTHON_DEFAULT_EXECUTABLE=$(which python3) \
-D PYTHON3_EXECUTABLE=$(which python3) \
-D PYTHON3_PACKAGES_PATH=$(python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())") \
-D WITH_OPENCL=ON ..
```

Even after all this, I end with 

```bash 
--   Python 3:
--     Interpreter:                 /data/data/com.termux/files/usr/bin/python3 (ver 3.8.1)
--     Libraries:                   NO
--     numpy:                       /data/data/com.termux/files/usr/lib/python3.8/site-packages/numpy-1.18.0-py3.8-linux-aarch64.egg/numpy/core/include (ver )
--     install path:                -
```

Here are the Details Cmake Details : 

Output of `termux-info`

```
Android version:
10
Kernel build information:
Linux localhost 4.9.179-perf+ #1 SMP PREEMPT Wed Jan 15 19:28:25 CST 2020 aarch64 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A6010

```

```
-- General configuration for OpenCV 4.2.0-dev =====================================
--   Version control:               4.2.0-276-gaa2777ed61
-- 
--   Platform:
--     Timestamp:                   2020-02-11T18:18:02Z
--     Host:                        Android 4.9.179-perf+ aarch64
--     CMake:                       3.16.4
--     CMake generator:             Unix Makefiles
--     CMake build tool:            /data/data/com.termux/files/usr/bin/make
--     Configuration:               RELEASE
-- 
--   CPU/HW features:
--     Baseline:                    NEON FP16
-- 
--   C/C++:
--     Built as dynamic libs?:      NO
--     C++ Compiler:                /data/data/com.termux/files/usr/bin/c++  (ver 9.0.1)
--     C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments    -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
--     C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments    -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
--     C Compiler:                  /data/data/com.termux/files/usr/bin/cc
--     C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments    -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
--     C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments    -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
--     Linker flags (Release):      -llog -lpython3  -Wl,--as-needed  
--     Linker flags (Debug):        -llog -lpython3  -Wl,--as-needed  
--     ccache:                      NO
--     Precompiled headers:         NO
--     Extra dependencies:          z dl m log
--     3rdparty dependencies:       libcpufeatures ittnotify libprotobuf libjpeg-turbo libwebp libpng libtiff libjasper IlmImf quirc tegra_hal
-- 
--   OpenCV modules:
--     To be built:                 calib3d core dnn features2d flann highgui imgcodecs imgproc ml objdetect photo stitching ts video videoio
--     Disabled:                    world
--     Disabled by dependency:      -
--     Unavailable:                 gapi java js python2 python3
--     Applications:                tests perf_tests
--     Documentation:               NO
--     Non-free algorithms:         NO
-- 
--   Android NDK:                   location: 
--     Android ABI:
--     STL type:
--     Native API level:
--   Android SDK:                   (tools:  build tools: )
-- 
--   GUI: 
-- 
--   Media I/O: 
--     ZLib:                        z (ver 1.2.11)
--     JPEG:                        build-libjpeg-turbo (ver 2.0.2-62)
--     WEBP:                        build (ver encoder: 0x020e)
--     PNG:                         build (ver 1.6.37)
--     TIFF:                        build (ver 42 - 4.0.10)
--     JPEG 2000:                   build (ver 1.900.1)
--     OpenEXR:                     build (ver 2.3.0)
--     HDR:                         YES
--     SUNRASTER:                   YES
--     PXM:                         YES
--     PFM:                         YES
-- 
--   Video I/O:
-- 
--   Parallel framework:            pthreads
-- 
--   Trace:                         YES (with Intel ITT)
-- 
--   Other third-party libraries:
--     Eigen:                       NO
--     Custom HAL:                  YES (carotene (ver 0.0.1))
--     Protobuf:                    build (3.5.1)
-- 
--   OpenCL:                        YES (no extra features)
--     Include path:                /data/data/com.termux/files/home/opencv/3rdparty/include/opencl/1.2
--     Link libraries:              Dynamic load
-- 
--   Python 3:
--     Interpreter:                 /data/data/com.termux/files/usr/bin/python3 (ver 3.8.1)
--     Libraries:                   NO
--     numpy:                       /data/data/com.termux/files/usr/lib/python3.8/site-packages/numpy-1.18.0-py3.8-linux-aarch64.egg/numpy/core/include (ver )
--     install path:                -
-- 
--   Python (for build):            /data/data/com.termux/files/usr/bin/python3
-- 
--   Install to:                    /data/data/com.termux/files/usr
-- -----------------------------------------------------------------

```

**Comment by its-pointless** [comment]
i cross compile this from docker image.

**Comment by its-pointless** [comment]
For now a hint building python modules requires me using linux instead of android to build it if i remember correctly it also tries to link . At some point i will share scripts but its kind of convoluted right now. 
-DPYTHON_EXECUTABLE=`which python2.7`                                                                                                                                                                   -DPYTHON3_EXECUTABLE=`which python3.8`                                                                                                                                                                  -DBUILD_opencv_python2=ON                                                                                                                                                                               -DBUILD_opencv_python3=ON                                                                                                                                                                               -DOPENCV_FORCE_PYTHON_LIBS=true                                                                                                                                                                         -DWITH_QT=OFF -DWITH_GTK=OFF  -DHAVE_CXX_MSSE4_1=off -DHAVE_CXX_MSSE4_2=off                                                                                                                             -DANDROID=NO                                                                                                                                                                                            -DENABLE_CCACHE=NO                                                                                                                                                                                      -DCMAKE_SYSTEM_NAME=Linux                                                                                                                                                                               -DPYTHON3_LIBRARIES=/data/data/com.termux/files/usr/lib                                                                                                                                                 -DPYTHON3_INCLUDE_PATH=/data/data/com.termux/files/usr/include/python3.8                                                                                                                                -DPYTHON2_LIBRARIES=/data/data/com.termux/files/usr/lib                                                                                                                                                 -DPYTHON2_INCLUDE_PATH=/data/data/com.termux/files/usr/include/python2.7                                                                                                                                -DBUILD_TESTS=no                                                                                                                                                                                        -DOPENCV_FORCE_PYTHON_LIBS=true                                                                                                                                                                         -DPNG_PNG_INCLUDE_DIR=/data/data/com.termux/files/usr/include                                                                                                                                           -DPNG_LIBRARY=/data/data/com.termux/files/usr/lib/libpng.so                                                                                                                                             -DWITH_V4L=OFF                                                                                                                                                                                          -DBUILD_PERF_TESTS=no                                                                                                                                                                                   -DPYTHON3_LIBRARIES="-lpython3.8"                                                                                                                                                                       -DPYTHON2_LIBRARIES="-lpython2.7"                                                                                                                                                                       -DPROTOBUF_UPDATE_FILES=ON                                                                                                                                                                              -DProtobuf_LIBRARY=$TERMUX_PREFIX/lib/libprotobuf.so                                                                                                                                                    -DPROTOBUF_INCLUDE_DIR=$TERMUX_PREFIX/include                                                                                                                                                           -DBUILD_PROTOBUF=OFF                                                                                                                                                                                    -DPROTOBUF_GENERATE_CPP=on                                                                                                                                                                              -DPYTHON3_EXECUTABLE=/usr/bin/python3.8                                                                                                                                                                 -DPYTHON2_EXECUTABLE=/usr/bin/python2.7
-DPYTHON3_NUMPY_VERSION=1.18.0                                                                                                                                                                          -DPYTHON2_NUMPY_VERSION=1.16.5                                      
should be indictive
